[project]
name = "simpleqa-verified_2"
description = "SimpleQA verified benchmark with 1000 questions"
tags = ["qa","nlp","eval"]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.1.0",
    "openai>=1.107.3",
    "pip>=25.2",
    "verifiers>=0.1.3.post0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["simpleqa_verified_2.py"]
