[project]
name = "writing-bench"
description = "WritingBench eval environment"
tags = ["llm-as-judge", "long-form-text", "custom-prompt"]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "verifiers>=0.1.3",
    "json_repair"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["writing_bench.py"]