[project]
name = "deep-consult"
description = "Pairwise evaluation environment for consulting-style research reports, using rubric-based GPT metrics to compare responses on instruction following, comprehensiveness, completeness, and writing quality."
tags = ["consulting", "deep-research", "train", "eval"]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "verifiers>=0.1.3.post0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["deep_consult.py"]
