max_steps = 500
batch_size = 512
micro_batch_size = 1
seq_len = 8192
rollouts_per_example = 4
mask_truncated_completions = true

mask_env_responses = true

[model]
name = "willcb/Qwen3-1.7B"

[monitor.wandb]
project = "search-r1-ish"

[environment]
id = "search-r1-ish"

[environment.args]
judge_model = "deepseek-chat"
judge_base_url = "https://api.deepseek.com"
retriever = "bm25"
retrieval_server_url = "http://localhost:8099"

[sampling]


[monitor.wandb.log_extras]
interval = 10

[eval]
interval = 50

[ckpt]
