[project]
name = "psycho-bench"
description = "PsychoBench per‑instrument and per‑subscale evaluation for LLMs"
tags = ["psychology","personality","single-turn","eval"]
version = "0.1.1"
requires-python = ">=3.11"
dependencies = [
    "verifiers>=0.1.3.post0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["psycho_bench.py"]
