[project]
name = "uq"
description = "Evaluate language models on genuinely unsolved questions from Stack Exchange using oracle-free validation strategies with 3-stage sequential pipeline"
tags = ["unsolved-questions", "oracle-free", "validation", "reasoning", "stack-exchange", "research", "eval"]
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "verifiers>=0.1.3.post0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["uq.py"]
