[project]
name = "skyrl-sql"
version = "0.1.0"
license = "MIT"
description = "Multi-turn Text-to-SQL environment with interactive database feedback following SkyRL-SQL methodology"
tags = ["sql", "text-to-sql", "multi-turn", "database", "reinforcement-learning", "train", "eval"]
requires-python = ">=3.11"
dependencies = [
    "verifiers>=0.1.3",
    "datasets",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["skyrl_sql.py"]
