[project]
name = "antislop"
version = "0.1.0"
description = "Rank model on anti-slop score"
tags = ["single-turn", "creative-writing", "llm-judge"]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "verifiers>=0.1.3.post0",
    "beautifulsoup4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["antislop.py"]
