[project]
name = "search-r1-ish"
version = "0.1.0"
description = "A RL environment for QA with a search tool over web or wikipedia"
tags = ["rl", "search", "rag", "train"]
dependencies = [
    "datasets>=4.0.0",
    "exa-py>=1.15.2",
    "fastapi>=0.116.1",
    "pyserini>=1.2.0",
    "requests>=2.32.5",
    "torch>=2.7.0",
    "transformers>=4.56.0",
    "uvicorn>=0.35.0",
    "verifiers>=0.1.3",
    "numpy>2",
    "faiss-cpu>=1.12.0",
    "huggingface-hub[cli]>=0.34.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["search_r1_ish.py"]




